EFM32 Giant Gecko Software Documentation: Unmod_Carrier_Plugin
Unmod_Carrier_Plugin
EMDRV » EZRADIODRV » Plugin_System
Detailed Description
Unmodulated Carrier plugin, see Plugin System Layer for detailed documentation.
.
Data Structures
struct EZRADIODRV_UnmodCarrierHandle
EzRadio unmodulated carrier plug-in instance initialization and handler structure.
Macros
#define EZRADIODRV_UNMOD_CARRIER_PLUGIN_INIT_DEFAULT
Configuration data for EzRadio unmodulated carrier plug-in.
Typedefs
typedef struct EZRADIODRV_UnmodCarrierHandle EZRADIODRV_UnmodCarrierHandle_t
EzRadio unmodulated carrier plug-in instance initialization and handler structure.
Functions
Ecode_t ezradioStartUnmodulatedCarrier (EZRADIODRV_Handle_t radioHandle)
Starts unmodulated carrier transmission with the radio configurations from the radioHandle parameter.
Ecode_t ezradioStopUnmodulatedCarrier (void)
Stops unmodulated carrier transmission.
Macro Definition Documentation
#define EZRADIODRV_UNMOD_CARRIER_PLUGIN_INIT_DEFAULT
Value:
{                               /* Unmodulated Carrier              */  \
  0,                            /* Channel                          */  \
},
Configuration data for EzRadio unmodulated carrier plug-in.
Definition at line 75 of file ezradio_unmod_carrier_plugin.h.
Function Documentation
Ecode_t ezradioStartUnmodulatedCarrier (EZRADIODRV_Handle_t radioHandle)
Starts unmodulated carrier transmission with the radio configurations from the radioHandle parameter.
Parameters
radioHandle Handler of the EzRadio driver instance where channel configuration is set.
Returns
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 57 of file ezradio_unmod_carrier_plugin.c.
References EZRADIODRV_UnmodCarrierHandle::channel, ECODE_EMDRV_EZRADIODRV_ILLEGAL_HANDLE, ECODE_EMDRV_EZRADIODRV_OK, ECODE_EMDRV_EZRADIODRV_TRANSMIT_FAILED, ezradio_get_int_status(), ezradio_request_device_state(), ezradio_start_tx(), and EZRADIODRV_HandleData::unmodCarrier.
Ecode_t ezradioStopUnmodulatedCarrier (void)
Stops unmodulated carrier transmission.
Returns
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 89 of file ezradio_unmod_carrier_plugin.c.
References ECODE_EMDRV_EZRADIODRV_OK, and ezradio_change_state().