EFM32 Zero Gecko Software Documentation: Direct_Receive_Plugin
Direct_Receive_Plugin
EMDRV » EZRADIODRV » Plugin_System
Detailed Description
Direct receive plugin, see Plugin System Layer for detailed documentation.
.
Data Structures
struct EZRADIODRV_DirectRxHandle
EzRadio direct rx plug-in instance initialization and handler structure.
Macros
#define EZRADIODRV_DIRECT_RECEIVE_PLUGIN_INIT_DEFAULT
Configuration data for EzRadio direct rx plug-in.
Typedefs
typedef struct EZRADIODRV_DirectRxHandle EZRADIODRV_DirectRxHandle_t
EzRadio direct rx plug-in instance initialization and handler structure.
Functions
Ecode_t ezradioStartDirectReceive (EZRADIODRV_Handle_t radioHandle)
Starts direct reception with the radio configurations from the radioHandle parameter.
Ecode_t ezradioStopDirectReceive (void)
Stops direct reception.
Macro Definition Documentation
#define EZRADIODRV_DIRECT_RECEIVE_PLUGIN_INIT_DEFAULT
Value:
{                               /* PN9                              */  \
  0,                            /* Channel                          */  \
},
Configuration data for EzRadio direct rx plug-in.
Definition at line 75 of file ezradio_direct_receive_plugin.h.
Function Documentation
Ecode_t ezradioStartDirectReceive (EZRADIODRV_Handle_t radioHandle)
Starts direct reception with the radio configurations from the radioHandle parameter.
Parameters
radioHandle Handler of the EzRadio driver instance where channel configuration is set.
Returns
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 56 of file ezradio_direct_receive_plugin.c.
References EZRADIODRV_DirectRxHandle::channel, EZRADIODRV_HandleData::directRx, ECODE_EMDRV_EZRADIODRV_ILLEGAL_HANDLE, ECODE_EMDRV_EZRADIODRV_OK, ezradio_get_int_status(), and ezradio_start_rx().
Ecode_t ezradioStopDirectReceive (void)
Stops direct reception.
Returns
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 82 of file ezradio_direct_receive_plugin.c.
References ECODE_EMDRV_EZRADIODRV_OK, and ezradio_change_state().