var group__Parts =
[
    [ "EFM32ZG222F32", "group__EFM32ZG222F32.html", "group__EFM32ZG222F32" ],
    [ "EFM32ZG_ACMP", "group__EFM32ZG__ACMP.html", "group__EFM32ZG__ACMP" ],
    [ "EFM32ZG_ACMP_BitFields", "group__EFM32ZG__ACMP__BitFields.html", "group__EFM32ZG__ACMP__BitFields" ],
    [ "EFM32ZG_ADC", "group__EFM32ZG__ADC.html", "group__EFM32ZG__ADC" ],
    [ "EFM32ZG_ADC_BitFields", "group__EFM32ZG__ADC__BitFields.html", "group__EFM32ZG__ADC__BitFields" ],
    [ "EFM32ZG_AES", "group__EFM32ZG__AES.html", "group__EFM32ZG__AES" ],
    [ "EFM32ZG_AES_BitFields", "group__EFM32ZG__AES__BitFields.html", "group__EFM32ZG__AES__BitFields" ],
    [ "EFM32ZG_AF_Pins", "group__EFM32ZG__AF__Pins.html", "group__EFM32ZG__AF__Pins" ],
    [ "EFM32ZG_AF_Ports", "group__EFM32ZG__AF__Ports.html", "group__EFM32ZG__AF__Ports" ],
    [ "EFM32ZG_CALIBRATE", "group__EFM32ZG__CALIBRATE.html", "group__EFM32ZG__CALIBRATE" ],
    [ "EFM32ZG_CMU", "group__EFM32ZG__CMU.html", "group__EFM32ZG__CMU" ],
    [ "EFM32ZG_CMU_BitFields", "group__EFM32ZG__CMU__BitFields.html", "group__EFM32ZG__CMU__BitFields" ],
    [ "EFM32ZG_DEVINFO", "group__EFM32ZG__DEVINFO.html", "group__EFM32ZG__DEVINFO" ],
    [ "EFM32ZG_DEVINFO_BitFields", "group__EFM32ZG__DEVINFO__BitFields.html", "group__EFM32ZG__DEVINFO__BitFields" ],
    [ "EFM32ZG_DMA", "group__EFM32ZG__DMA.html", "group__EFM32ZG__DMA" ],
    [ "EFM32ZG_DMACTRL_BitFields", "group__EFM32ZG__DMACTRL__BitFields.html", "group__EFM32ZG__DMACTRL__BitFields" ],
    [ "EFM32ZG_DMAREQ_BitFields", "group__EFM32ZG__DMAREQ__BitFields.html", "group__EFM32ZG__DMAREQ__BitFields" ],
    [ "EFM32ZG_DMA_BitFields", "group__EFM32ZG__DMA__BitFields.html", "group__EFM32ZG__DMA__BitFields" ],
    [ "EFM32ZG_DMA_DESCRIPTOR", "group__EFM32ZG__DMA__DESCRIPTOR.html", "group__EFM32ZG__DMA__DESCRIPTOR" ],
    [ "EFM32ZG_EMU", "group__EFM32ZG__EMU.html", "group__EFM32ZG__EMU" ],
    [ "EFM32ZG_EMU_BitFields", "group__EFM32ZG__EMU__BitFields.html", "group__EFM32ZG__EMU__BitFields" ],
    [ "EFM32ZG_GPIO", "group__EFM32ZG__GPIO.html", "group__EFM32ZG__GPIO" ],
    [ "EFM32ZG_GPIO_BitFields", "group__EFM32ZG__GPIO__BitFields.html", "group__EFM32ZG__GPIO__BitFields" ],
    [ "EFM32ZG_I2C", "group__EFM32ZG__I2C.html", "group__EFM32ZG__I2C" ],
    [ "EFM32ZG_I2C_BitFields", "group__EFM32ZG__I2C__BitFields.html", "group__EFM32ZG__I2C__BitFields" ],
    [ "EFM32ZG_IDAC", "group__EFM32ZG__IDAC.html", "group__EFM32ZG__IDAC" ],
    [ "EFM32ZG_IDAC_BitFields", "group__EFM32ZG__IDAC__BitFields.html", "group__EFM32ZG__IDAC__BitFields" ],
    [ "EFM32ZG_LEUART", "group__EFM32ZG__LEUART.html", "group__EFM32ZG__LEUART" ],
    [ "EFM32ZG_LEUART_BitFields", "group__EFM32ZG__LEUART__BitFields.html", "group__EFM32ZG__LEUART__BitFields" ],
    [ "EFM32ZG_MSC", "group__EFM32ZG__MSC.html", "group__EFM32ZG__MSC" ],
    [ "EFM32ZG_MSC_BitFields", "group__EFM32ZG__MSC__BitFields.html", "group__EFM32ZG__MSC__BitFields" ],
    [ "EFM32ZG_PCNT", "group__EFM32ZG__PCNT.html", "group__EFM32ZG__PCNT" ],
    [ "EFM32ZG_PCNT_BitFields", "group__EFM32ZG__PCNT__BitFields.html", "group__EFM32ZG__PCNT__BitFields" ],
    [ "EFM32ZG_PRS", "group__EFM32ZG__PRS.html", "group__EFM32ZG__PRS" ],
    [ "EFM32ZG_PRS_BitFields", "group__EFM32ZG__PRS__BitFields.html", "group__EFM32ZG__PRS__BitFields" ],
    [ "EFM32ZG_PRS_Signals", "group__EFM32ZG__PRS__Signals.html", "group__EFM32ZG__PRS__Signals" ],
    [ "EFM32ZG_RMU", "group__EFM32ZG__RMU.html", "group__EFM32ZG__RMU" ],
    [ "EFM32ZG_RMU_BitFields", "group__EFM32ZG__RMU__BitFields.html", "group__EFM32ZG__RMU__BitFields" ],
    [ "EFM32ZG_ROMTABLE", "group__EFM32ZG__ROMTABLE.html", "group__EFM32ZG__ROMTABLE" ],
    [ "EFM32ZG_ROMTABLE_BitFields", "group__EFM32ZG__ROMTABLE__BitFields.html", "group__EFM32ZG__ROMTABLE__BitFields" ],
    [ "EFM32ZG_RTC", "group__EFM32ZG__RTC.html", "group__EFM32ZG__RTC" ],
    [ "EFM32ZG_RTC_BitFields", "group__EFM32ZG__RTC__BitFields.html", "group__EFM32ZG__RTC__BitFields" ],
    [ "EFM32ZG_TIMER", "group__EFM32ZG__TIMER.html", "group__EFM32ZG__TIMER" ],
    [ "EFM32ZG_TIMER_BitFields", "group__EFM32ZG__TIMER__BitFields.html", "group__EFM32ZG__TIMER__BitFields" ],
    [ "EFM32ZG_USART", "group__EFM32ZG__USART.html", "group__EFM32ZG__USART" ],
    [ "EFM32ZG_USART_BitFields", "group__EFM32ZG__USART__BitFields.html", "group__EFM32ZG__USART__BitFields" ],
    [ "EFM32ZG_VCMP", "group__EFM32ZG__VCMP.html", "group__EFM32ZG__VCMP" ],
    [ "EFM32ZG_VCMP_BitFields", "group__EFM32ZG__VCMP__BitFields.html", "group__EFM32ZG__VCMP__BitFields" ],
    [ "EFM32ZG_WDOG", "group__EFM32ZG__WDOG.html", "group__EFM32ZG__WDOG" ],
    [ "EFM32ZG_WDOG_BitFields", "group__EFM32ZG__WDOG__BitFields.html", "group__EFM32ZG__WDOG__BitFields" ],
    [ "DMA_CH_TypeDef", "structDMA__CH__TypeDef.html", [
      [ "CTRL", "structDMA__CH__TypeDef.html#a42c320e31a3b152836f99c5b414378df", null ]
    ] ],
    [ "GPIO_P_TypeDef", "structGPIO__P__TypeDef.html", [
      [ "CTRL", "structGPIO__P__TypeDef.html#a473a74fcee9b697cf642c887f167e900", null ],
      [ "DIN", "structGPIO__P__TypeDef.html#a8d6bab03ea08dc3e2408dbead3f69e99", null ],
      [ "DOUT", "structGPIO__P__TypeDef.html#ad49eb368c1fb770c9b3873f27d7f3cf0", null ],
      [ "DOUTCLR", "structGPIO__P__TypeDef.html#a48b9bb92719a589c4983c4115d3aab1f", null ],
      [ "DOUTSET", "structGPIO__P__TypeDef.html#a621cfc6fd02e0d852be38d0d66f0a6e9", null ],
      [ "DOUTTGL", "structGPIO__P__TypeDef.html#ac71a9aad29711f2a75831535cbd2848e", null ],
      [ "MODEH", "structGPIO__P__TypeDef.html#a4ee759a562af28eccb7c297bfc618855", null ],
      [ "MODEL", "structGPIO__P__TypeDef.html#a5418724025e260191444b876c75da4bb", null ],
      [ "PINLOCKN", "structGPIO__P__TypeDef.html#ae2004e79e252f39747bd7ab68d4d2022", null ]
    ] ],
    [ "PRS_CH_TypeDef", "structPRS__CH__TypeDef.html", [
      [ "CTRL", "structPRS__CH__TypeDef.html#a87aaa9a0fa4b70a4e86e3334756ba262", null ]
    ] ],
    [ "TIMER_CC_TypeDef", "structTIMER__CC__TypeDef.html", [
      [ "CCV", "structTIMER__CC__TypeDef.html#a08171cad28467b1a803b3557cc1127d7", null ],
      [ "CCVB", "structTIMER__CC__TypeDef.html#a954e0fd8b3bda78f99106ad3ebb7fa0f", null ],
      [ "CCVP", "structTIMER__CC__TypeDef.html#a1345286209ed7a06df44020b776103ca", null ],
      [ "CTRL", "structTIMER__CC__TypeDef.html#a6cc61bb28f687753c3527f6d0ccfba27", null ]
    ] ]
];