EFR32 Blue Gecko 12 Software Documentation: Tft
Tft
Kit Drivers
Detailed Description
Functions
void SPI_TFT_Init (void)
SPI_TFT_Init Initialize SPI interface to TFT-LCD SSD2119 controller.
void SPI_TFT_WriteRegister (uint8_t reg, uint16_t data)
SPI_TFT_Write Write registers/data to SSD2119 controller.
bool TFT_AddressMappedInit (void)
TFT initialize or reinitialize to Address Mapped Mode Assumes EBI has been configured correctly in BSP_Init(BSP_INIT_DK_EBI)
void TFT_DirectGPIOConfig (void)
GPIO configuration for TFT direct drive.
bool TFT_DirectInit (const EBI_TFTInit_TypeDef *tftInit)
TFT initialize or reinitialize Assumes EBI has been configured correctly in BSP_Init(BSP_INIT_DK_EBI)
Function Documentation
void SPI_TFT_Init (void)
SPI_TFT_Init Initialize SPI interface to TFT-LCD SSD2119 controller.
Note
To enable access, be sure to call the functions BSP_PeripheralAccess(BSP_TFT, enable); before using this interface.
Definition at line 45 of file tftspi.c.
References CMU_ClockEnable(), cmuClock_GPIO, cmuClock_HFPER, cmuClock_USART1, GPIO_PinModeSet(), gpioModeInput, gpioModePushPull, USART1, USART_InitSync(), and USART_Reset().
void SPI_TFT_WriteRegister (uint8_t reg, uint16_t data)
SPI_TFT_Write Write registers/data to SSD2119 controller.
Parameters
reg Register to write to
data 16-bit data to write into register
Note
It's not possible to read back register value through SSD2119 SPI interface, so no SPI_TFT_ReadRegister function is implemented
Definition at line 82 of file tftspi.c.
References GPIO_PinOutClear(), GPIO_PinOutSet(), USART1, USART_CTRL_BIT8DV, USART_Rx(), and USART_Tx().
bool TFT_AddressMappedInit (void)
TFT initialize or reinitialize to Address Mapped Mode Assumes EBI has been configured correctly in BSP_Init(BSP_INIT_DK_EBI)
Returns
true if we should redraw into buffer, false if BC has control over display
Definition at line 37 of file tftamapped.c.
References BC_ARB_CTRL_EBI, BC_REGISTER, BC_SPI_DEMUX_SLAVE_AUDIO, BC_SPI_DEMUX_SLAVE_DISPLAY, BC_SSD2119_BASE, BC_UIF_AEM_EFM, BSP_Display_EBI, BSP_Display_Mode8080, BSP_Display_PowerDisable, BSP_Display_PowerEnable, BSP_Display_ResetAssert, BSP_Display_ResetRelease, BSP_DisplayControl(), BSP_RegisterRead(), BSP_RegisterWrite(), runOnce, and SystemCoreClockGet().
bool TFT_DirectInit (const EBI_TFTInit_TypeDef * tftInit)
TFT initialize or reinitialize Assumes EBI has been configured correctly in BSP_Init(BSP_INIT_DK_EBI)
Parameters
[in] tftInit Pointer to EBI TFT initialization structure
Returns
true if we should redraw into buffer, false if BC has control over display
Definition at line 54 of file tftdirect.c.
References BC_ARB_CTRL_EBI, BC_REGISTER, BC_UIF_AEM_EFM, BSP_Display_EBI, BSP_Display_ModeGeneric, BSP_Display_PowerDisable, BSP_Display_PowerEnable, BSP_Display_ResetAssert, BSP_Display_ResetRelease, BSP_DisplayControl(), BSP_PeripheralAccess(), BSP_RegisterRead(), BSP_TFT, runOnce, SystemCoreClockGet(), and TFT_DirectGPIOConfig().