EFR32 Mighty Gecko 1 Software Documentation: Plugin_Manager
Plugin_Manager
EMDRV » EZRADIODRV » Plugin_System
Detailed Description
Plugin manager, see Plugin System Layer for detailed documentation.
.
Data Structures
struct EZRADIODRV_HandleData
Macros
#define ECODE_EMDRV_EZRADIODRV_AUTO_ACK_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000400)
Receive plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_CRC_ERROR_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000300)
CRC error plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_DIRECT_RECEIVE_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000800)
Receive plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_DIRECT_TRANSMIT_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000700)
Transmit plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_ILLEGAL_HANDLE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000001)
Illegal SPI handle.
#define ECODE_EMDRV_EZRADIODRV_OK (ECODE_OK)
Success return value.
#define ECODE_EMDRV_EZRADIODRV_PN9_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000600)
Receive plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_RECEIVE_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000200)
Receive plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_TRANSMIT_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000100)
Transmit plugin base error code.
#define ECODE_EMDRV_EZRADIODRV_UNMOD_CARRIER_PLUGIN_BASE (ECODE_EMDRV_EZRADIODRV_BASE | 0x00000500)
Receive plugin base error code.
#define EZRADIODRV_INIT_DEFAULT
Configuration data for EzRadio plugin manager.
#define RADIO_CONFIG_DATA_FIELD_LENGTH
#define RADIO_CONFIG_DATA_MAX_PACKET_LENGTH RADIO_CONFIG_DATA_FIELD1_LENGTH
Typedefs
typedef void(* EZRADIODRV_Callback_t) (EZRADIODRV_Handle_t handle, Ecode_t status)
EZRADIODRV feature callback function interface.
typedef EZRADIODRV_HandleData_t * EZRADIODRV_Handle_t
EZRadio driver instance handle.
typedef struct EZRADIODRV_HandleData EZRADIODRV_HandleData_t
Interface for EZRADIODRV_HandleData structure type defined below.
typedef ezradio_cmd_reply_t * EZRADIODRV_ReplyHandle_t
EZradio reply union handle.
Functions
void ezradioInit (EZRADIODRV_Handle_t handle)
Radio Initialization.
Ecode_t ezradioPluginManager (EZRADIODRV_Handle_t handle)
EzRadio plugin manager state machine handler. This function should be called in the application in an infinite loop, in order to manage the EzRadio plug-ins properly.
void ezradioResetTRxFifo (void)
Resets both the TX and RX FIFOs.
Macro Definition Documentation
#define EZRADIODRV_INIT_DEFAULT
Value:
{                                                                             \
  EZRADIODRV_TRANSMIT_PLUGIN_INIT_DEFAULT         /* Tx plugin init */        \
  EZRADIODRV_RECEIVE_PLUGIN_INIT_DEFAULT          /* Rx plugin init */        \
  EZRADIODRV_CRC_ERROR_PLUGIN_INIT_DEFAULT        /* CRC error plugin init */ \
  EZRADIODRV_AUTO_ACK_PLUGIN_INIT_DEFAULT         /* Auto-ack plugin init */  \
  EZRADIODRV_UNMOD_CARRIER_PLUGIN_INIT_DEFAULT    /* CW plugin init */        \
  EZRADIODRV_PN9_PLUGIN_INIT_DEFAULT              /* PN9 plugin init */       \
  EZRADIODRV_DIRECT_TRANSMIT_PLUGIN_INIT_DEFAULT  /* Direct Tx plugin init */ \
  EZRADIODRV_DIRECT_RECEIVE_PLUGIN_INIT_DEFAULT   /* Direct Rx plugin init */ \
}
Configuration data for EzRadio plugin manager.
Definition at line 344 of file ezradio_plugin_manager.h.
#define RADIO_CONFIG_DATA_FIELD_LENGTH
Value:
{ \
   RADIO_CONFIG_DATA_FIELD1_LENGTH, \
   0u, \
   0u, \
   0u, \
   0u, \
   }
Definition at line 144 of file ezradio_plugin_manager.h.
Typedef Documentation
typedef void(* EZRADIODRV_Callback_t) (EZRADIODRV_Handle_t handle, Ecode_t status)
EZRADIODRV feature callback function interface.
Parameters
[in] handle EZRadioDrv instance handler.
[in] status Callback status.
Returns
None
Definition at line 284 of file ezradio_plugin_manager.h.
Function Documentation
void ezradioInit (EZRADIODRV_Handle_t handle)
Radio Initialization.
Parameters
[in] handle EzRadio driver instance handler.
Definition at line 81 of file ezradio_plugin_manager.c.
References EZRADIO_CONFIG_SUCCESS, ezradio_configuration_init(), ezradio_get_int_status(), ezradio_hal_GpioInit(), ezradio_hal_SpiInit(), USTIMER_DeInit(), USTIMER_Delay(), and USTIMER_Init().
Ecode_t ezradioPluginManager (EZRADIODRV_Handle_t radioHandle)
EzRadio plugin manager state machine handler. This function should be called in the application in an infinite loop, in order to manage the EzRadio plug-ins properly.
Parameters
[in] radioHandle EzRadio driver instance handler.
Definition at line 128 of file ezradio_plugin_manager.c.
References ECODE_EMDRV_EZRADIODRV_ILLEGAL_HANDLE, ECODE_EMDRV_EZRADIODRV_OK, and ezradio_get_int_status().