var group__Parts =
[
    [ "EFM32G890F128", "group__EFM32G890F128.html", "group__EFM32G890F128" ],
    [ "EFM32G_ACMP", "group__EFM32G__ACMP.html", "group__EFM32G__ACMP" ],
    [ "EFM32G_ACMP_BitFields", "group__EFM32G__ACMP__BitFields.html", "group__EFM32G__ACMP__BitFields" ],
    [ "EFM32G_ADC", "group__EFM32G__ADC.html", "group__EFM32G__ADC" ],
    [ "EFM32G_ADC_BitFields", "group__EFM32G__ADC__BitFields.html", "group__EFM32G__ADC__BitFields" ],
    [ "EFM32G_AES", "group__EFM32G__AES.html", "group__EFM32G__AES" ],
    [ "EFM32G_AES_BitFields", "group__EFM32G__AES__BitFields.html", "group__EFM32G__AES__BitFields" ],
    [ "EFM32G_AF_Pins", "group__EFM32G__AF__Pins.html", "group__EFM32G__AF__Pins" ],
    [ "EFM32G_AF_Ports", "group__EFM32G__AF__Ports.html", "group__EFM32G__AF__Ports" ],
    [ "EFM32G_CALIBRATE", "group__EFM32G__CALIBRATE.html", "group__EFM32G__CALIBRATE" ],
    [ "EFM32G_CMU", "group__EFM32G__CMU.html", "group__EFM32G__CMU" ],
    [ "EFM32G_CMU_BitFields", "group__EFM32G__CMU__BitFields.html", "group__EFM32G__CMU__BitFields" ],
    [ "EFM32G_DAC", "group__EFM32G__DAC.html", "group__EFM32G__DAC" ],
    [ "EFM32G_DAC_BitFields", "group__EFM32G__DAC__BitFields.html", "group__EFM32G__DAC__BitFields" ],
    [ "EFM32G_DEVINFO", "group__EFM32G__DEVINFO.html", "group__EFM32G__DEVINFO" ],
    [ "EFM32G_DEVINFO_BitFields", "group__EFM32G__DEVINFO__BitFields.html", "group__EFM32G__DEVINFO__BitFields" ],
    [ "EFM32G_DMA", "group__EFM32G__DMA.html", "group__EFM32G__DMA" ],
    [ "EFM32G_DMACTRL_BitFields", "group__EFM32G__DMACTRL__BitFields.html", "group__EFM32G__DMACTRL__BitFields" ],
    [ "EFM32G_DMAREQ_BitFields", "group__EFM32G__DMAREQ__BitFields.html", "group__EFM32G__DMAREQ__BitFields" ],
    [ "EFM32G_DMA_BitFields", "group__EFM32G__DMA__BitFields.html", "group__EFM32G__DMA__BitFields" ],
    [ "EFM32G_DMA_DESCRIPTOR", "group__EFM32G__DMA__DESCRIPTOR.html", "group__EFM32G__DMA__DESCRIPTOR" ],
    [ "EFM32G_EBI", "group__EFM32G__EBI.html", "group__EFM32G__EBI" ],
    [ "EFM32G_EBI_BitFields", "group__EFM32G__EBI__BitFields.html", "group__EFM32G__EBI__BitFields" ],
    [ "EFM32G_EMU", "group__EFM32G__EMU.html", "group__EFM32G__EMU" ],
    [ "EFM32G_EMU_BitFields", "group__EFM32G__EMU__BitFields.html", "group__EFM32G__EMU__BitFields" ],
    [ "EFM32G_GPIO", "group__EFM32G__GPIO.html", "group__EFM32G__GPIO" ],
    [ "EFM32G_GPIO_BitFields", "group__EFM32G__GPIO__BitFields.html", "group__EFM32G__GPIO__BitFields" ],
    [ "EFM32G_I2C", "group__EFM32G__I2C.html", "group__EFM32G__I2C" ],
    [ "EFM32G_I2C_BitFields", "group__EFM32G__I2C__BitFields.html", "group__EFM32G__I2C__BitFields" ],
    [ "EFM32G_LCD", "group__EFM32G__LCD.html", "group__EFM32G__LCD" ],
    [ "EFM32G_LCD_BitFields", "group__EFM32G__LCD__BitFields.html", "group__EFM32G__LCD__BitFields" ],
    [ "EFM32G_LETIMER", "group__EFM32G__LETIMER.html", "group__EFM32G__LETIMER" ],
    [ "EFM32G_LETIMER_BitFields", "group__EFM32G__LETIMER__BitFields.html", "group__EFM32G__LETIMER__BitFields" ],
    [ "EFM32G_LEUART", "group__EFM32G__LEUART.html", "group__EFM32G__LEUART" ],
    [ "EFM32G_LEUART_BitFields", "group__EFM32G__LEUART__BitFields.html", "group__EFM32G__LEUART__BitFields" ],
    [ "EFM32G_MSC", "group__EFM32G__MSC.html", "group__EFM32G__MSC" ],
    [ "EFM32G_MSC_BitFields", "group__EFM32G__MSC__BitFields.html", "group__EFM32G__MSC__BitFields" ],
    [ "EFM32G_PCNT", "group__EFM32G__PCNT.html", "group__EFM32G__PCNT" ],
    [ "EFM32G_PCNT_BitFields", "group__EFM32G__PCNT__BitFields.html", "group__EFM32G__PCNT__BitFields" ],
    [ "EFM32G_PRS", "group__EFM32G__PRS.html", "group__EFM32G__PRS" ],
    [ "EFM32G_PRS_BitFields", "group__EFM32G__PRS__BitFields.html", "group__EFM32G__PRS__BitFields" ],
    [ "EFM32G_PRS_Signals", "group__EFM32G__PRS__Signals.html", "group__EFM32G__PRS__Signals" ],
    [ "EFM32G_RMU", "group__EFM32G__RMU.html", "group__EFM32G__RMU" ],
    [ "EFM32G_RMU_BitFields", "group__EFM32G__RMU__BitFields.html", "group__EFM32G__RMU__BitFields" ],
    [ "EFM32G_ROMTABLE", "group__EFM32G__ROMTABLE.html", "group__EFM32G__ROMTABLE" ],
    [ "EFM32G_ROMTABLE_BitFields", "group__EFM32G__ROMTABLE__BitFields.html", "group__EFM32G__ROMTABLE__BitFields" ],
    [ "EFM32G_RTC", "group__EFM32G__RTC.html", "group__EFM32G__RTC" ],
    [ "EFM32G_RTC_BitFields", "group__EFM32G__RTC__BitFields.html", "group__EFM32G__RTC__BitFields" ],
    [ "EFM32G_TIMER", "group__EFM32G__TIMER.html", "group__EFM32G__TIMER" ],
    [ "EFM32G_TIMER_BitFields", "group__EFM32G__TIMER__BitFields.html", "group__EFM32G__TIMER__BitFields" ],
    [ "EFM32G_UART_BitFields", "group__EFM32G__UART__BitFields.html", "group__EFM32G__UART__BitFields" ],
    [ "EFM32G_USART", "group__EFM32G__USART.html", "group__EFM32G__USART" ],
    [ "EFM32G_USART_BitFields", "group__EFM32G__USART__BitFields.html", "group__EFM32G__USART__BitFields" ],
    [ "EFM32G_VCMP", "group__EFM32G__VCMP.html", "group__EFM32G__VCMP" ],
    [ "EFM32G_VCMP_BitFields", "group__EFM32G__VCMP__BitFields.html", "group__EFM32G__VCMP__BitFields" ],
    [ "EFM32G_WDOG", "group__EFM32G__WDOG.html", "group__EFM32G__WDOG" ],
    [ "EFM32G_WDOG_BitFields", "group__EFM32G__WDOG__BitFields.html", "group__EFM32G__WDOG__BitFields" ],
    [ "DMA_CH_TypeDef", "structDMA__CH__TypeDef.html", [
      [ "CTRL", "structDMA__CH__TypeDef.html#a42c320e31a3b152836f99c5b414378df", null ]
    ] ],
    [ "GPIO_P_TypeDef", "structGPIO__P__TypeDef.html", [
      [ "CTRL", "structGPIO__P__TypeDef.html#a473a74fcee9b697cf642c887f167e900", null ],
      [ "DIN", "structGPIO__P__TypeDef.html#a8d6bab03ea08dc3e2408dbead3f69e99", null ],
      [ "DOUT", "structGPIO__P__TypeDef.html#ad49eb368c1fb770c9b3873f27d7f3cf0", null ],
      [ "DOUTCLR", "structGPIO__P__TypeDef.html#a48b9bb92719a589c4983c4115d3aab1f", null ],
      [ "DOUTSET", "structGPIO__P__TypeDef.html#a621cfc6fd02e0d852be38d0d66f0a6e9", null ],
      [ "DOUTTGL", "structGPIO__P__TypeDef.html#ac71a9aad29711f2a75831535cbd2848e", null ],
      [ "MODEH", "structGPIO__P__TypeDef.html#a4ee759a562af28eccb7c297bfc618855", null ],
      [ "MODEL", "structGPIO__P__TypeDef.html#a5418724025e260191444b876c75da4bb", null ],
      [ "PINLOCKN", "structGPIO__P__TypeDef.html#ae2004e79e252f39747bd7ab68d4d2022", null ]
    ] ],
    [ "PRS_CH_TypeDef", "structPRS__CH__TypeDef.html", [
      [ "CTRL", "structPRS__CH__TypeDef.html#a87aaa9a0fa4b70a4e86e3334756ba262", null ]
    ] ],
    [ "TIMER_CC_TypeDef", "structTIMER__CC__TypeDef.html", [
      [ "CCV", "structTIMER__CC__TypeDef.html#a08171cad28467b1a803b3557cc1127d7", null ],
      [ "CCVB", "structTIMER__CC__TypeDef.html#a954e0fd8b3bda78f99106ad3ebb7fa0f", null ],
      [ "CCVP", "structTIMER__CC__TypeDef.html#a1345286209ed7a06df44020b776103ca", null ],
      [ "CTRL", "structTIMER__CC__TypeDef.html#a6cc61bb28f687753c3527f6d0ccfba27", null ]
    ] ]
];