EFM32 Pearl Gecko 1 Software Documentation: EMU
EMU
EMLIB
Detailed Description
Energy Management Unit (EMU) Peripheral API.
This module contains functions to control the EMU peripheral of Silicon Labs 32-bit MCUs and SoCs. The EMU handles the different low energy modes in Silicon Labs microcontrollers.
Data Structures
struct EMU_DCDCInit_TypeDef
struct EMU_EM23Init_TypeDef
struct EMU_EM4Init_TypeDef
struct EMU_VmonHystInit_TypeDef
struct EMU_VmonInit_TypeDef
Macros
#define EMU_DCDCINIT_DEFAULT
#define EMU_EM23INIT_DEFAULT
#define EMU_EM4INIT_DEFAULT
#define EMU_VMONHYSTINIT_DEFAULT
#define EMU_VMONINIT_DEFAULT
#define emuDcdcLnFastTransient 160
#define emuDcdcLnHighEfficiency -1
#define PWRCFG_DCDCTODVDD_VMAX 3000
#define PWRCFG_DCDCTODVDD_VMIN 1800
Typedefs
typedef int16_t EMU_DcdcLnReverseCurrentControl_TypeDef
Enumerations
enum EMU_BiasMode_TypeDef {
emuBiasMode_1KHz,
emuBiasMode_4KHz,
emuBiasMode_Continuous
}
enum EMU_BODMode_TypeDef {
emuBODMode_Active,
emuBODMode_Inactive
}
enum EMU_DcdcAnaPeripheralPower_TypeDef {
emuDcdcAnaPeripheralPower_AVDD = EMU_PWRCTRL_ANASW_AVDD,
emuDcdcAnaPeripheralPower_DCDC = EMU_PWRCTRL_ANASW_DVDD
}
enum EMU_DcdcConductionMode_TypeDef {
emuDcdcConductionMode_ContinuousLN,
emuDcdcConductionMode_DiscontinuousLN
}
enum EMU_DcdcLnCompCtrl_TypeDef {
emuDcdcLnCompCtrl_1u0F,
emuDcdcLnCompCtrl_4u7F
}
enum EMU_DcdcLnRcoBand_TypeDef {
emuDcdcLnRcoBand_3MHz = 0,
emuDcdcLnRcoBand_4MHz = 1,
emuDcdcLnRcoBand_5MHz = 2,
emuDcdcLnRcoBand_6MHz = 3,
emuDcdcLnRcoBand_7MHz = 4,
emuDcdcLnRcoBand_8MHz = 5,
emuDcdcLnRcoBand_9MHz = 6,
emuDcdcLnRcoBand_10MHz = 7
}
enum EMU_DcdcMode_TypeDef {
emuDcdcMode_Bypass = EMU_DCDCCTRL_DCDCMODE_BYPASS,
emuDcdcMode_LowNoise = EMU_DCDCCTRL_DCDCMODE_LOWNOISE
}
enum EMU_EM4PinRetention_TypeDef {
emuPinRetentionDisable = EMU_EM4CTRL_EM4IORETMODE_DISABLE,
emuPinRetentionEm4Exit = EMU_EM4CTRL_EM4IORETMODE_EM4EXIT,
emuPinRetentionLatch = EMU_EM4CTRL_EM4IORETMODE_SWUNLATCH
}
enum EMU_EM4State_TypeDef {
emuEM4Hibernate = EMU_EM4CTRL_EM4STATE_EM4H,
emuEM4Shutoff = EMU_EM4CTRL_EM4STATE_EM4S
}
enum EMU_PowerConfig_TypeDef { emuPowerConfig_DcdcToDvdd }
enum EMU_VmonChannel_TypeDef {
emuVmonChannel_AVDD,
emuVmonChannel_ALTAVDD,
emuVmonChannel_DVDD,
emuVmonChannel_IOVDD0
}
Functions
void EMU_DCDCConductionModeSet (EMU_DcdcConductionMode_TypeDef conductionMode, bool rcoDefaultSet)
Set DCDC LN regulator conduction mode.
bool EMU_DCDCInit (const EMU_DCDCInit_TypeDef *dcdcInit)
Configure DCDC regulator.
void EMU_DCDCLnRcoBandSet (EMU_DcdcLnRcoBand_TypeDef band)
Set DCDC Low-noise RCO band.
void EMU_DCDCModeSet (EMU_DcdcMode_TypeDef dcdcMode)
Set DCDC regulator operating mode.
void EMU_DCDCOptimizeSlice (uint32_t em0LoadCurrent_mA)
Optimize DCDC slice count based on the estimated average load current in EM0.
bool EMU_DCDCOutputVoltageSet (uint32_t mV, bool setLpVoltage, bool setLnVoltage)
Set DCDC output voltage.
bool EMU_DCDCPowerOff (void)
Power off the DCDC regulator.
void EMU_EM23Init (const EMU_EM23Init_TypeDef *em23Init)
Update EMU module with Energy Mode 2 and 3 configuration.
__STATIC_INLINE void EMU_EM2Block (void)
Block entering EM2 or higher number energy modes.
__STATIC_INLINE void EMU_EM2UnBlock (void)
Unblock entering EM2 or higher number energy modes.
void EMU_EM4Init (const EMU_EM4Init_TypeDef *em4Init)
Update EMU module with Energy Mode 4 configuration.
__STATIC_INLINE void EMU_EnterEM1 (void)
Enter energy mode 1 (EM1).
void EMU_EnterEM2 (bool restore)
Enter energy mode 2 (EM2).
void EMU_EnterEM3 (bool restore)
Enter energy mode 3 (EM3).
void EMU_EnterEM4 (void)
Enter energy mode 4 (EM4).
void EMU_EnterEM4H (void)
Enter energy mode 4 hibernate (EM4H).
void EMU_EnterEM4S (void)
Enter energy mode 4 shutoff (EM4S).
__STATIC_INLINE void EMU_IntClear (uint32_t flags)
Clear one or more pending EMU interrupts.
__STATIC_INLINE void EMU_IntDisable (uint32_t flags)
Disable one or more EMU interrupts.
__STATIC_INLINE void EMU_IntEnable (uint32_t flags)
Enable one or more EMU interrupts.
__STATIC_INLINE uint32_t EMU_IntGet (void)
Get pending EMU interrupt flags.
__STATIC_INLINE uint32_t EMU_IntGetEnabled (void)
Get enabled and pending EMU interrupt flags. Useful for handling more interrupt sources in the same interrupt handler.
__STATIC_INLINE void EMU_IntSet (uint32_t flags)
Set one or more pending EMU interrupts.
__STATIC_INLINE void EMU_Lock (void)
Lock the EMU in order to protect its registers against unintended modification.
void EMU_MemPwrDown (uint32_t blocks)
Power down memory block.
__STATIC_INLINE void EMU_PowerLock (void)
Lock the EMU regulator control registers in order to protect against unintended modification.
__STATIC_INLINE void EMU_PowerUnlock (void)
Unlock the EMU power control registers so that writing to locked registers again is possible.
void EMU_RamPowerDown (uint32_t start, uint32_t end)
Power down RAM memory blocks.
void EMU_Restore (void)
Restore CMU HF clock select state, oscillator enable and voltage scaling (if available) after EMU_EnterEM2() or EMU_EnterEM3() are called with the restore parameter set to false. Calling this function is equivalent to calling EMU_EnterEM2() or EMU_EnterEM3() with the restore parameter set to true, but it allows the application to evaluate the wakeup reason before restoring state.
void EMU_SetBiasMode (EMU_BiasMode_TypeDef mode)
Adjust the bias refresh rate.
__STATIC_INLINE void EMU_UnlatchPinRetention (void)
When EM4 pin retention is set to emuPinRetentionLatch, then pins are retained through EM4 entry and wakeup. The pin state is released by calling this function. The feature allows peripherals or GPIO to be re-initialized after EM4 exit (reset), and when the initialization is done, this function can release pins and return control to the peripherals or GPIO.
__STATIC_INLINE void EMU_Unlock (void)
Unlock the EMU so that writing to locked registers again is possible.
void EMU_UpdateOscConfig (void)
Update EMU module with CMU oscillator selection/enable status.
bool EMU_VmonChannelStatusGet (EMU_VmonChannel_TypeDef channel)
Get the status of a voltage monitor channel.
void EMU_VmonEnable (EMU_VmonChannel_TypeDef channel, bool enable)
Enable or disable a VMON channel.
void EMU_VmonHystInit (const EMU_VmonHystInit_TypeDef *vmonInit)
Initialize VMON channel with hysteresis (separate rise and fall triggers).
void EMU_VmonInit (const EMU_VmonInit_TypeDef *vmonInit)
Initialize VMON channel.
__STATIC_INLINE bool EMU_VmonStatusGet (void)
Get the status of the voltage monitor (VMON).
Macro Definition Documentation
#define EMU_DCDCINIT_DEFAULT
Value:
{                                                                                                               \
  emuPowerConfig_DcdcToDvdd,     /* DCDC to DVDD */                                                             \
  emuDcdcMode_LowNoise,          /* Low-niose mode in EM0 */                                                    \
  1800,                          /* Nominal output voltage for DVDD mode, 1.8V  */                              \
  5,                             /* Nominal EM0/1 load current of less than 5mA */                              \
  10,                            /* Nominal EM2/3/4 load current less than 10uA  */                             \
  200,                           /* Maximum average current of 200mA
                                    (assume strong battery or other power source) */                            \
  emuDcdcAnaPeripheralPower_DCDC,/* Select DCDC as analog power supply (lower power) */                         \
  emuDcdcLnHighEfficiency,       /* Use high-efficiency mode */                                                 \
  emuDcdcLnCompCtrl_1u0F,        /* 1uF DCDC capacitor */                                                       \
}
Default DCDC initialization
Definition at line 551 of file em_emu.h.
#define EMU_EM23INIT_DEFAULT
Value:
{                                                                                                               \
  false,                                                /* Reduced voltage regulator drive strength in EM2/3 */ \
}
Default initialization of EM2 and 3 configuration
Definition at line 404 of file em_emu.h.
#define EMU_EM4INIT_DEFAULT
Value:
{                                                                                          \
  false,                             /* Retain LFXO configuration upon EM4 entry */        \
  false,                             /* Retain LFRCO configuration upon EM4 entry */       \
  false,                             /* Retain ULFRCO configuration upon EM4 entry */      \
  emuEM4Shutoff,                     /* Use EM4 shutoff state */                           \
  emuPinRetentionDisable,            /* Do not retain pins in EM4 */                       \
}
Default initialization of EM4 configuration (Series 1 without VSCALE)
Definition at line 460 of file em_emu.h.
Referenced by UTIL_shutdown().
#define EMU_VMONHYSTINIT_DEFAULT
Value:
{                                                                                  \
  emuVmonChannel_AVDD,                  /* AVDD VMON channel */                    \
  3200,                                 /* 3.2 V rise threshold */                 \
  3200,                                 /* 3.2 V fall threshold */                 \
  false,                                /* Don't wake from EM4H on rising edge */  \
  false,                                /* Don't wake from EM4H on falling edge */ \
  true                                  /* Enable VMON channel */                  \
}
Default VMON Hysteresis initialization structure
Definition at line 648 of file em_emu.h.
#define EMU_VMONINIT_DEFAULT
Value:
{                                                                                  \
  emuVmonChannel_AVDD,                  /* AVDD VMON channel */                    \
  3200,                                 /* 3.2 V threshold */                      \
  false,                                /* Don't wake from EM4H on rising edge */  \
  false,                                /* Don't wake from EM4H on falling edge */ \
  true,                                 /* Enable VMON channel */                  \
  false                                 /* Don't disable IO0 retention */          \
}
Default VMON initialization structure
Definition at line 626 of file em_emu.h.
#define emuDcdcLnFastTransient 160
Default reverse current for fast transient response mode (low noise).
Definition at line 209 of file em_emu.h.
#define emuDcdcLnHighEfficiency -1
High efficiency mode. EMU_DCDCZDETCTRL_ZDETILIMSEL is "don't care".
Definition at line 206 of file em_emu.h.
Typedef Documentation
typedef int16_t EMU_DcdcLnReverseCurrentControl_TypeDef
DCDC Forced CCM and reverse current limiter control. Positive values have unit mA.
Definition at line 203 of file em_emu.h.
Enumeration Type Documentation
enum EMU_BiasMode_TypeDef
Bias mode configurations
Definition at line 274 of file em_emu.h.
enum EMU_BODMode_TypeDef
BOD threshold setting selector, active or inactive mode
Enumerator
emuBODMode_Active
Configure BOD threshold for active mode
emuBODMode_Inactive
Configure BOD threshold for inactive mode
Definition at line 121 of file em_emu.h.
enum EMU_DcdcAnaPeripheralPower_TypeDef
DCDC to DVDD mode analog peripheral power supply select
Enumerator
emuDcdcAnaPeripheralPower_AVDD
Select AVDD as analog power supply. Typically lower noise, but less energy efficient.
emuDcdcAnaPeripheralPower_DCDC
Select DCDC (DVDD) as analog power supply. Typically more energy efficient, but more noise.
Definition at line 192 of file em_emu.h.
enum EMU_DcdcConductionMode_TypeDef
DCDC conduction modes
Enumerator
emuDcdcConductionMode_ContinuousLN
DCDC Low-Noise Continuous Conduction Mode (CCM). EFR32 interference minimization features are available in this mode.
emuDcdcConductionMode_DiscontinuousLN
DCDC Low-Noise Discontinuous Conduction Mode (DCM). This mode should be used for EFM32 or when the EFR32 radio is not enabled.
Definition at line 179 of file em_emu.h.
enum EMU_DcdcLnCompCtrl_TypeDef
DCDC Low Noise Compensator Control register.
Enumerator
emuDcdcLnCompCtrl_1u0F
DCDC capacitor is 1uF.
emuDcdcLnCompCtrl_4u7F
DCDC capacitor is 4.7uF.
Definition at line 251 of file em_emu.h.
enum EMU_DcdcLnRcoBand_TypeDef
DCDC Low-noise RCO band select
Enumerator
emuDcdcLnRcoBand_3MHz
Set RCO to 3MHz
emuDcdcLnRcoBand_4MHz
Set RCO to 4MHz
emuDcdcLnRcoBand_5MHz
Set RCO to 5MHz
emuDcdcLnRcoBand_6MHz
Set RCO to 6MHz
emuDcdcLnRcoBand_7MHz
Set RCO to 7MHz
emuDcdcLnRcoBand_8MHz
Set RCO to 8MHz
emuDcdcLnRcoBand_9MHz
Set RCO to 9MHz
emuDcdcLnRcoBand_10MHz
Set RCO to 10MHz
Definition at line 215 of file em_emu.h.
enum EMU_DcdcMode_TypeDef
DCDC operating modes
Enumerator
emuDcdcMode_Bypass
DCDC regulator bypass
emuDcdcMode_LowNoise
DCDC low-noise mode
Definition at line 164 of file em_emu.h.
enum EMU_EM4PinRetention_TypeDef
Enumerator
emuPinRetentionDisable
No Retention: Pads enter reset state when entering EM4
emuPinRetentionEm4Exit
Retention through EM4: Pads enter reset state when exiting EM4
emuPinRetentionLatch
Retention through EM4 and wakeup: call EMU_UnlatchPinRetention() to release pins from retention after EM4 wakeup
Definition at line 142 of file em_emu.h.
enum EMU_EM4State_TypeDef
EM4 modes
Enumerator
emuEM4Hibernate
EM4 Hibernate
emuEM4Shutoff
EM4 Shutoff
Definition at line 131 of file em_emu.h.
enum EMU_PowerConfig_TypeDef
Power configurations. DCDC-to-DVDD is currently the only supported mode.
Enumerator
emuPowerConfig_DcdcToDvdd
DCDC is connected to DVDD
Definition at line 155 of file em_emu.h.
enum EMU_VmonChannel_TypeDef
VMON channels
Definition at line 263 of file em_emu.h.
Function Documentation
void EMU_DCDCConductionModeSet (EMU_DcdcConductionMode_TypeDef conductionMode, bool rcoDefaultSet)
Set DCDC LN regulator conduction mode.
Parameters
[in] conductionMode DCDC LN conduction mode.
[in] rcoDefaultSet The default DCDC RCO band for the conductionMode will be used if true. Otherwise the current RCO configuration is used.
Definition at line 1813 of file em_emu.c.
References _EMU_DCDCCTRL_DCDCMODE_MASK, _EMU_DCDCLNFREQCTRL_RCOBAND_MASK, _EMU_DCDCLNFREQCTRL_RCOBAND_SHIFT, EMU, EMU_DCDCLnRcoBandSet(), EMU_DCDCMISCCTRL_LNFORCECCM, EMU_DCDCModeSet(), EMU_DCDCOptimizeSlice(), EMU_DCDCSYNC_DCDCCTRLBUSY, EMU_IF_DCDCINBYPASS, EMU_IFC_DCDCINBYPASS, EMU_IntClear(), EMU_IntGet(), emuDcdcConductionMode_DiscontinuousLN, emuDcdcLnRcoBand_3MHz, emuDcdcLnRcoBand_4MHz, emuDcdcLnRcoBand_7MHz, and emuDcdcMode_Bypass.
bool EMU_DCDCInit (const EMU_DCDCInit_TypeDef * dcdcInit)
Configure DCDC regulator.
Note
If the power circuit is configured for NODCDC as described in Section 11.3.4.3 of the Reference Manual, do not call this function. Instead call EMU_DCDCPowerOff().
Parameters
[in] dcdcInit DCDC initialization structure
Returns
True if initialization parameters are valid
Definition at line 1869 of file em_emu.c.
References _EMU_DCDCMISCCTRL_LNFORCECCM_MASK, _EMU_PWRCFG_PWRCFG_MASK, _EMU_PWRCTRL_ANASW_SHIFT, EMU_DCDCInit_TypeDef::anaPeripheralPower, BUS_RegBitWrite(), EMU_DCDCInit_TypeDef::dcdcLnCompCtrl, EMU_DCDCInit_TypeDef::dcdcMode, EMU_DCDCInit_TypeDef::em01LoadCurrent_mA, EMU_DCDCInit_TypeDef::em234LoadCurrent_uA, EMU, EMU_DCDCMISCCTRL_LNFORCECCM, EMU_DCDCModeSet(), EMU_DCDCOptimizeSlice(), EMU_DCDCOutputVoltageSet(), EMU_PWRCFG_PWRCFG_DCDCTODVDD, emuDcdcMode_LowNoise, EMU_DCDCInit_TypeDef::maxCurrent_mA, EMU_DCDCInit_TypeDef::mVout, and EMU_DCDCInit_TypeDef::reverseCurrentControl.
void EMU_DCDCLnRcoBandSet (EMU_DcdcLnRcoBand_TypeDef band)
Set DCDC Low-noise RCO band.
Parameters
[in] band RCO band to set.
Definition at line 2260 of file em_emu.c.
References _EMU_DCDCLNFREQCTRL_RCOBAND_MASK, _EMU_DCDCLNFREQCTRL_RCOBAND_SHIFT, _EMU_DCDCMISCCTRL_LNFORCECCM_SHIFT, BUS_RegBitRead(), EMU, EMU_DCDCOptimizeSlice(), and emuDcdcLnRcoBand_4MHz.
Referenced by EMU_DCDCConductionModeSet().
void EMU_DCDCModeSet (EMU_DcdcMode_TypeDef dcdcMode)
Set DCDC regulator operating mode.
Parameters
[in] dcdcMode DCDC mode
Definition at line 1760 of file em_emu.c.
References _EMU_DCDCCLIMCTRL_BYPLIMEN_SHIFT, _EMU_DCDCCTRL_DCDCMODE_MASK, BUS_RegBitWrite(), EMU, EMU_DCDCCTRL_DCDCMODE_BYPASS, EMU_DCDCCTRL_DCDCMODE_LOWNOISE, EMU_DCDCCTRL_DCDCMODE_OFF, EMU_DCDCSYNC_DCDCCTRLBUSY, EMU_IF_DCDCLNRUNNING, EMU_IFC_DCDCLNRUNNING, EMU_IntClear(), EMU_IntGet(), emuDcdcMode_Bypass, and emuDcdcMode_LowNoise.
Referenced by EMU_DCDCConductionModeSet(), EMU_DCDCInit(), and EMU_EnterEM4().
void EMU_DCDCOptimizeSlice (uint32_t em0LoadCurrent_mA)
Optimize DCDC slice count based on the estimated average load current in EM0.
Parameters
[in] em0LoadCurrent_mA Estimated average EM0 load current in mA.
Definition at line 2184 of file em_emu.c.
References _EMU_DCDCLNFREQCTRL_RCOBAND_MASK, _EMU_DCDCLNFREQCTRL_RCOBAND_SHIFT, _EMU_DCDCMISCCTRL_LNFORCECCM_MASK, _EMU_DCDCMISCCTRL_NFETCNT_MASK, _EMU_DCDCMISCCTRL_NFETCNT_SHIFT, _EMU_DCDCMISCCTRL_PFETCNT_MASK, _EMU_DCDCMISCCTRL_PFETCNT_SHIFT, EMU, emuDcdcLnRcoBand_4MHz, and emuDcdcLnRcoBand_5MHz.
Referenced by EMU_DCDCConductionModeSet(), EMU_DCDCInit(), and EMU_DCDCLnRcoBandSet().
bool EMU_DCDCOutputVoltageSet (uint32_t mV, bool setLpVoltage, bool setLnVoltage)
Set DCDC output voltage.
Parameters
[in] mV Target DCDC output voltage in mV
Returns
True if the mV parameter is valid
Definition at line 2020 of file em_emu.c.
References _DEVINFO_DCDCLNVCTRL0_1V2LNATT0_MASK, _DEVINFO_DCDCLNVCTRL0_1V2LNATT0_SHIFT, _DEVINFO_DCDCLNVCTRL0_1V8LNATT0_MASK, _DEVINFO_DCDCLNVCTRL0_1V8LNATT0_SHIFT, _DEVINFO_DCDCLNVCTRL0_1V8LNATT1_MASK, _DEVINFO_DCDCLNVCTRL0_1V8LNATT1_SHIFT, _DEVINFO_DCDCLNVCTRL0_3V0LNATT1_MASK, _DEVINFO_DCDCLNVCTRL0_3V0LNATT1_SHIFT, _EMU_DCDCLNVCTRL_LNATT_MASK, _EMU_DCDCLNVCTRL_LNVREF_MASK, _EMU_DCDCLNVCTRL_LNVREF_SHIFT, _EMU_DCDCLPVCTRL_LPATT_MASK, _EMU_DCDCLPVCTRL_LPVREF_MASK, _EMU_DCDCLPVCTRL_LPVREF_SHIFT, DEVINFO, EMU, EMU_DCDCLNVCTRL_LNATT, EMU_DCDCLPVCTRL_LPATT, SL_MAX, and SL_MIN.
Referenced by EMU_DCDCInit().
bool EMU_DCDCPowerOff (void)
Power off the DCDC regulator.
This function powers off the DCDC controller. This function should only be used if the external power circuit is wired for no DCDC. If the external power circuit is wired for DCDC usage, then use EMU_DCDCInit() and set the DCDC in bypass mode to disable DCDC.
Returns
Return false if the DCDC could not be disabled.
Definition at line 2288 of file em_emu.c.
References EMU, EMU_DCDCCTRL_DCDCMODE_OFF, EMU_DCDCSYNC_DCDCCTRLBUSY, and EMU_PWRCFG_PWRCFG_DCDCTODVDD.
void EMU_EM23Init (const EMU_EM23Init_TypeDef * em23Init)
Update EMU module with Energy Mode 2 and 3 configuration.
Parameters
[in] em23Init Energy Mode 2 and 3 configuration structure
Definition at line 1078 of file em_emu.c.
References EMU_EM23Init_TypeDef::em23VregFullEn, and EMU.
void EMU_EM4Init (const EMU_EM4Init_TypeDef * em4Init)
Update EMU module with Energy Mode 4 configuration.
Parameters
[in] em4Init Energy Mode 4 configuration structure
Definition at line 1105 of file em_emu.c.
References _EMU_EM4CTRL_EM4IORETMODE_MASK, _EMU_EM4CTRL_EM4STATE_MASK, _EMU_EM4CTRL_RETAINLFRCO_MASK, _EMU_EM4CTRL_RETAINLFXO_MASK, _EMU_EM4CTRL_RETAINULFRCO_MASK, EMU_EM4Init_TypeDef::em4State, EMU, EMU_EM4CTRL_EM4STATE_EM4H, EMU_EM4CTRL_RETAINLFRCO, EMU_EM4CTRL_RETAINLFXO, EMU_EM4CTRL_RETAINULFRCO, EMU_EM4Init_TypeDef::pinRetentionMode, EMU_EM4Init_TypeDef::retainLfrco, EMU_EM4Init_TypeDef::retainLfxo, and EMU_EM4Init_TypeDef::retainUlfrco.
Referenced by UTIL_shutdown().
void EMU_EnterEM2 (bool restore)
Enter energy mode 2 (EM2).
When entering EM2, the high frequency clocks are disabled, ie HFXO, HFRCO and AUXHFRCO (for AUXHFRCO, see exception note below). When re-entering EM0, HFRCO is re-enabled and the core will be clocked by the configured HFRCO band. This ensures a quick wakeup from EM2.
However, prior to entering EM2, the core may have been using another oscillator than HFRCO. The restore parameter gives the user the option to restore all HF oscillators according to state prior to entering EM2, as well as the clock used to clock the core. This restore procedure is handled by SW. However, since handled by SW, it will not be restored before completing the interrupt function(s) waking up the core!
Note
If restoring core clock to use the HFXO oscillator, which has been disabled during EM2 mode, this function will stall until the oscillator has stabilized. Stalling time can be reduced by adding interrupt support detecting stable oscillator, and an asynchronous switch to the original oscillator. See CMU documentation. Such a feature is however outside the scope of the implementation in this function.
If HFXO is re-enabled by this function, and NOT used to clock the core, this function will not wait for HFXO to stabilize. This must be considered by the application if trying to use features relying on that oscillator upon return.
If a debugger is attached, the AUXHFRCO will not be disabled if enabled upon entering EM2. It will thus remain enabled when returning to EM0 regardless of the restore parameter.
If HFXO autostart and select is enabled by using CMU_HFXOAutostartEnable(), the starting and selecting of the core clocks will be identical to the user independently of the value of the restore parameter when waking up on the wakeup sources corresponding to the autostart and select setting.
If voltage scaling is supported, the restore parameter is true and the EM0 voltage scaling level is set higher than the EM2 level, then the EM0 level is also restored.
Parameters
[in] restore
true - restore oscillators, clocks and voltage scaling, see function details.
false - do not restore oscillators and clocks, see function details.
The restore option should only be used if all clock control is done via the CMU API.
Definition at line 480 of file em_emu.c.
References SystemCoreClockUpdate().
Referenced by CAPLESENSE_Sleep(), UTIL_sleep(), and UTIL_waitForEvent().
void EMU_EnterEM3 (bool restore)
Enter energy mode 3 (EM3).
When entering EM3, the high frequency clocks are disabled by HW, ie HFXO, HFRCO and AUXHFRCO (for AUXHFRCO, see exception note below). In addition, the low frequency clocks, ie LFXO and LFRCO are disabled by SW. When re-entering EM0, HFRCO is re-enabled and the core will be clocked by the configured HFRCO band. This ensures a quick wakeup from EM3.
However, prior to entering EM3, the core may have been using another oscillator than HFRCO. The restore parameter gives the user the option to restore all HF/LF oscillators according to state prior to entering EM3, as well as the clock used to clock the core. This restore procedure is handled by SW. However, since handled by SW, it will not be restored before completing the interrupt function(s) waking up the core!
Note
If restoring core clock to use an oscillator other than HFRCO, this function will stall until the oscillator has stabilized. Stalling time can be reduced by adding interrupt support detecting stable oscillator, and an asynchronous switch to the original oscillator. See CMU documentation. Such a feature is however outside the scope of the implementation in this function.
If HFXO/LFXO/LFRCO are re-enabled by this function, and NOT used to clock the core, this function will not wait for those oscillators to stabilize. This must be considered by the application if trying to use features relying on those oscillators upon return.
If a debugger is attached, the AUXHFRCO will not be disabled if enabled upon entering EM3. It will thus remain enabled when returning to EM0 regardless of the restore parameter.
If voltage scaling is supported, the restore parameter is true and the EM0 voltage scaling level is set higher than the EM3 level, then the EM0 level is also restored.
Parameters
[in] restore
true - restore oscillators, clocks and voltage scaling, see function details.
false - do not restore oscillators and clocks, see function details.
The restore option should only be used if all clock control is done via the CMU API.
Definition at line 597 of file em_emu.c.
References CMU, CMU_Lock(), CMU_LOCK_LOCKKEY_LOCKED, CMU_OSCENCMD_LFRCODIS, CMU_OSCENCMD_LFXODIS, CMU_Unlock(), and SystemCoreClockUpdate().
void EMU_EnterEM4 (void)
Enter energy mode 4 (EM4).
Note
Only a power on reset or external reset pin can wake the device from EM4.
Definition at line 705 of file em_emu.c.
References _EMU_DCDCCTRL_DCDCMODE_MASK, _EMU_EM4CTRL_EM4ENTRY_MASK, _EMU_EM4CTRL_EM4ENTRY_SHIFT, _EMU_EM4CTRL_EM4STATE_MASK, EMU, EMU_BASE, EMU_DCDCCTRL_DCDCMODE_LOWNOISE, EMU_DCDCCTRL_DCDCMODE_LOWPOWER, EMU_DCDCModeSet(), EMU_EM4CTRL_EM4STATE_EM4H, EMU_EM4CTRL_EM4STATE_EM4S, EMU_Unlock(), and emuDcdcMode_Bypass.
Referenced by EMU_EnterEM4H(), EMU_EnterEM4S(), and UTIL_shutdown().
void EMU_EnterEM4H (void)
Enter energy mode 4 hibernate (EM4H).
Note
Retention of clocks and GPIO in EM4 can be configured using EMU_EM4Init before calling this function.
Definition at line 787 of file em_emu.c.
References _EMU_EM4CTRL_EM4STATE_SHIFT, BUS_RegBitWrite(), EMU, and EMU_EnterEM4().
void EMU_EnterEM4S (void)
Enter energy mode 4 shutoff (EM4S).
Note
Retention of clocks and GPIO in EM4 can be configured using EMU_EM4Init before calling this function.
Definition at line 801 of file em_emu.c.
References _EMU_EM4CTRL_EM4STATE_SHIFT, BUS_RegBitWrite(), EMU, and EMU_EnterEM4().
__STATIC_INLINE void EMU_IntClear (uint32_t flags)
Clear one or more pending EMU interrupts.
Parameters
[in] flags Pending EMU interrupt sources to clear. Use one or more valid interrupt flags for the EMU module (EMU_IFC_nnn).
Definition at line 772 of file em_emu.h.
References EMU.
Referenced by disableInterrupts(), EMU_DCDCConductionModeSet(), EMU_DCDCModeSet(), and TEMPDRV_IRQHandler().
__STATIC_INLINE void EMU_IntDisable (uint32_t flags)
Disable one or more EMU interrupts.
Parameters
[in] flags EMU interrupt sources to disable. Use one or more valid interrupt flags for the EMU module (EMU_IEN_nnn).
Definition at line 786 of file em_emu.h.
References EMU.
Referenced by disableInterrupts(), and updateInterrupts().
__STATIC_INLINE void EMU_IntEnable (uint32_t flags)
Enable one or more EMU interrupts.
Note
Depending on the use, a pending interrupt may already be set prior to enabling the interrupt. Consider using EMU_IntClear() prior to enabling if such a pending interrupt should be ignored.
Parameters
[in] flags EMU interrupt sources to enable. Use one or more valid interrupt flags for the EMU module (EMU_IEN_nnn).
Definition at line 805 of file em_emu.h.
References EMU.
Referenced by updateInterrupts().
__STATIC_INLINE uint32_t EMU_IntGet (void)
Get pending EMU interrupt flags.
Note
The event bits are not cleared by the use of this function.
Returns
EMU interrupt sources pending. Returns one or more valid interrupt flags for the EMU module (EMU_IF_nnn).
Definition at line 822 of file em_emu.h.
References EMU.
Referenced by EMU_DCDCConductionModeSet(), and EMU_DCDCModeSet().
__STATIC_INLINE uint32_t EMU_IntGetEnabled (void)
Get enabled and pending EMU interrupt flags. Useful for handling more interrupt sources in the same interrupt handler.
Note
Interrupt flags are not cleared by the use of this function.
Returns
Pending and enabled EMU interrupt sources The return value is the bitwise AND of
the enabled interrupt sources in EMU_IEN and
the pending interrupt flags EMU_IF
Definition at line 842 of file em_emu.h.
References EMU.
Referenced by TEMPDRV_IRQHandler().
__STATIC_INLINE void EMU_IntSet (uint32_t flags)
Set one or more pending EMU interrupts.
Parameters
[in] flags EMU interrupt sources to set to pending. Use one or more valid interrupt flags for the EMU module (EMU_IFS_nnn).
Definition at line 859 of file em_emu.h.
References EMU.
__STATIC_INLINE void EMU_Lock (void)
Lock the EMU in order to protect its registers against unintended modification.
Note
If locking the EMU registers, they must be unlocked prior to using any EMU API functions modifying EMU registers, excluding interrupt control and regulator control if the architecture has a EMU_PWRCTRL register. An exception to this is the energy mode entering API (EMU_EnterEMn()), which can be used when the EMU registers are locked.
Definition at line 916 of file em_emu.h.
References EMU, and EMU_LOCK_LOCKKEY_LOCK.
Referenced by RMU_ResetCauseClear().
void EMU_MemPwrDown (uint32_t blocks)
Power down memory block.
Parameters
[in] blocks Specifies a logical OR of bits indicating memory blocks to power down. Bit 0 selects block 1, bit 1 selects block 2, etc. Memory block 0 cannot be disabled. Please refer to the reference manual for available memory blocks for a device.
Note
Only a POR reset can power up the specified memory block(s) after powerdown.
Deprecated:
This function is deprecated, use EMU_RamPowerDown() instead which maps a user provided memory range into RAM blocks to power down.
Definition at line 825 of file em_emu.c.
References _EMU_RAM0CTRL_MASK, and EMU.
void EMU_RamPowerDown (uint32_t start, uint32_t end)
Power down RAM memory blocks.
This function will power down all the RAM blocks that are within a given range. The RAM block layout is different between device families, so this function can be used in a generic way to power down a RAM memory region which is known to be unused.
This function will only power down blocks which are completely enclosed by the memory range given by [start, end).
Here is an example of how to power down all RAM blocks except the first one. The first RAM block is special in that it cannot be powered down by the hardware. The size of this first RAM block is device specific see the reference manual to find the RAM block sizes.
 EMU_RamPowerDown(SRAM_BASE, SRAM_BASE + SRAM_SIZE);
Note
Only a POR reset can power up the specified memory block(s) after powerdown.
Parameters
[in] start The start address of the RAM region to power down. This address is inclusive.
[in] end The end address of the RAM region to power down. This address is exclusive. If this parameter is 0, then all RAM blocks contained in the region from start to the upper RAM address will be powered down.
Definition at line 870 of file em_emu.c.
References EMU, RAM_MEM_BASE, SRAM_BASE, and SRAM_SIZE.
void EMU_SetBiasMode (EMU_BiasMode_TypeDef mode)
Adjust the bias refresh rate.
This function is only meant to be used under high-temperature operation on EFR32xG1 and EFM32xG1 devices. Adjusting the bias mode will increase the typical current consumption. See application note 1027 and errata documents for further details.
Parameters
[in] mode The new bias refresh rate
Definition at line 2522 of file em_emu.c.
Referenced by errataStateUpdate().
void EMU_UpdateOscConfig (void)
Update EMU module with CMU oscillator selection/enable status.
Deprecated:
Oscillator status is saved in EMU_EnterEM2() and EMU_EnterEM3().
Definition at line 958 of file em_emu.c.
bool EMU_VmonChannelStatusGet (EMU_VmonChannel_TypeDef channel)
Get the status of a voltage monitor channel.
Parameters
[in] channel VMON channel to get status for
Returns
Status of the selected VMON channel. True if channel is triggered.
Definition at line 2482 of file em_emu.c.
References _EMU_STATUS_VMONALTAVDD_SHIFT, _EMU_STATUS_VMONAVDD_SHIFT, _EMU_STATUS_VMONDVDD_SHIFT, _EMU_STATUS_VMONIO0_SHIFT, BUS_RegBitRead(), and EMU.
void EMU_VmonEnable (EMU_VmonChannel_TypeDef channel, bool enable)
Enable or disable a VMON channel.
Parameters
[in] channel VMON channel to enable/disable
[in] enable Whether to enable or disable
Definition at line 2441 of file em_emu.c.
References _EMU_VMONALTAVDDCTRL_EN_SHIFT, _EMU_VMONAVDDCTRL_EN_SHIFT, _EMU_VMONDVDDCTRL_EN_SHIFT, _EMU_VMONIO0CTRL_EN_SHIFT, BUS_RegBitWrite(), and EMU.
void EMU_VmonHystInit (const EMU_VmonHystInit_TypeDef * vmonInit)
Initialize VMON channel with hysteresis (separate rise and fall triggers).
Initialize a VMON channel which supports hysteresis. The AVDD channel is the only channel to support separate rise and fall triggers.
Parameters
[in] vmonInit VMON Hysteresis initialization struct
Definition at line 2400 of file em_emu.c.
References _EMU_VMONAVDDCTRL_FALLTHRESCOARSE_SHIFT, _EMU_VMONAVDDCTRL_FALLTHRESFINE_SHIFT, _EMU_VMONAVDDCTRL_RISETHRESCOARSE_SHIFT, _EMU_VMONAVDDCTRL_RISETHRESFINE_SHIFT, EMU_VmonHystInit_TypeDef::channel, EMU, EMU_VMONAVDDCTRL_EN, EMU_VMONAVDDCTRL_FALLWU, EMU_VMONAVDDCTRL_RISEWU, EMU_VmonHystInit_TypeDef::enable, EMU_VmonHystInit_TypeDef::fallThreshold, EMU_VmonHystInit_TypeDef::fallWakeup, EMU_VmonHystInit_TypeDef::riseThreshold, and EMU_VmonHystInit_TypeDef::riseWakeup.
void EMU_VmonInit (const EMU_VmonInit_TypeDef * vmonInit)
Initialize VMON channel.
Initialize a VMON channel without hysteresis. If the channel supports separate rise and fall triggers, both thresholds will be set to the same value.
Parameters
[in] vmonInit VMON initialization struct
Definition at line 2342 of file em_emu.c.
References _EMU_VMONALTAVDDCTRL_THRESCOARSE_SHIFT, _EMU_VMONALTAVDDCTRL_THRESFINE_SHIFT, _EMU_VMONAVDDCTRL_FALLTHRESCOARSE_SHIFT, _EMU_VMONAVDDCTRL_FALLTHRESFINE_SHIFT, _EMU_VMONAVDDCTRL_RISETHRESCOARSE_SHIFT, _EMU_VMONAVDDCTRL_RISETHRESFINE_SHIFT, _EMU_VMONDVDDCTRL_THRESCOARSE_SHIFT, _EMU_VMONDVDDCTRL_THRESFINE_SHIFT, _EMU_VMONIO0CTRL_THRESCOARSE_SHIFT, _EMU_VMONIO0CTRL_THRESFINE_SHIFT, EMU_VmonInit_TypeDef::channel, EMU, EMU_VMONALTAVDDCTRL_EN, EMU_VMONALTAVDDCTRL_FALLWU, EMU_VMONALTAVDDCTRL_RISEWU, EMU_VMONAVDDCTRL_EN, EMU_VMONAVDDCTRL_FALLWU, EMU_VMONAVDDCTRL_RISEWU, EMU_VMONDVDDCTRL_EN, EMU_VMONDVDDCTRL_FALLWU, EMU_VMONDVDDCTRL_RISEWU, EMU_VMONIO0CTRL_EN, EMU_VMONIO0CTRL_FALLWU, EMU_VMONIO0CTRL_RETDIS, EMU_VMONIO0CTRL_RISEWU, EMU_VmonInit_TypeDef::enable, EMU_VmonInit_TypeDef::fallWakeup, EMU_VmonInit_TypeDef::retDisable, EMU_VmonInit_TypeDef::riseWakeup, and EMU_VmonInit_TypeDef::threshold.
__STATIC_INLINE bool EMU_VmonStatusGet (void)
Get the status of the voltage monitor (VMON).
Returns
Status of the VMON. True if all the enabled channels are ready, false if one or more of the enabled channels are not ready.
Definition at line 757 of file em_emu.h.
References _EMU_STATUS_VMONRDY_SHIFT, BUS_RegBitRead(), and EMU.