EFM32 Leopard Gecko Software Documentation: RetargetSWO
RetargetSWO
Kit Drivers
Detailed Description
Functions
int RETARGET_ReadChar (void)
Receive a byte from USART/LEUART and put into global buffer.
int RETARGET_WriteChar (char c)
Transmit single byte to USART/LEUART.
void setupSWOForPrint (void)
Function Documentation
int RETARGET_ReadChar (void)
Receive a byte from USART/LEUART and put into global buffer.
Returns
-1 on failure, or positive character integer on sucesss
Receive a byte from USART/LEUART and put into global buffer.
Returns
-1 on failure
Receive a byte from USART/LEUART and put into global buffer.
Returns
-1 on failure, or positive character integer on sucesss
Definition at line 210 of file retargetserial.c.
References initialized, INT_Disable(), INT_Enable(), RETARGET_SerialInit(), rxBuffer, RXBUFSIZE, rxCount, and rxReadIndex.
int RETARGET_WriteChar (char c)
Transmit single byte to USART/LEUART.
Parameters
c Character to transmit
Returns
Transmitted character
Transmit single byte to USART/LEUART.
Parameters
c Character to write
Returns
Printed character if text display is initialized. -1 if text display is not initialized.
Transmit single byte to USART/LEUART.
Parameters
c Character to transmit
Returns
Transmitted character
Definition at line 240 of file retargetserial.c.
References BC_ARB_CTRL_EBI, BC_REGISTER, BC_UIF_AEM_EFM, BSP_RegisterRead(), bufferReset, fullUpdate, initialized, LFtoCRLF, RETARGET_SerialInit(), RETARGET_TFTTX(), RETARGET_TFTUpdate(), TEXTDISPLAY_WriteChar(), tftReset, and tftTextReset().