EZR32 Leopard Gecko Software Documentation: Touch
Touch
Kit Drivers
Detailed Description
Data Structures
struct TOUCH_Config_TypeDef
struct TOUCH_Pos_TypeDef
Macros
#define TOUCH_INIT_DEFAULT
Typedefs
typedef void(TOUCH_Upcall_TypeDef) (TOUCH_Pos_TypeDef *)
Functions
int TOUCH_CalibrationTable (POINT *displayPtr, POINT *screenPtr)
Set calibration table.
TOUCH_Pos_TypeDef * TOUCH_GetPos (void)
Returns current touch position and state.
void TOUCH_Init (TOUCH_Config_TypeDef *config)
Initialize touch panel driver.
int TOUCH_IsBusy (void)
Check status of the touch panel.
void TOUCH_RegisterUpcall (TOUCH_Upcall_TypeDef *new_upcall)
Register upcall which will be call every position or state change.
Macro Definition Documentation
#define TOUCH_INIT_DEFAULT
Value:
{ 500000,                /* 500kHz sampling frequency */             \
    1,                     /* Ignore moves not greater than 1 pixel */ \
    adcOvsRateSel128,      /* Oversampling 128 times */                \
  }
Initializes Touch default values
Definition at line 63 of file touch.h.
Typedef Documentation
typedef void(TOUCH_Upcall_TypeDef) (TOUCH_Pos_TypeDef *)
touch panel upcall type definition
Definition at line 70 of file touch.h.
Function Documentation
int TOUCH_CalibrationTable (POINT * displayPtr, POINT * screenPtr)
Set calibration table.
Parameters
[in] displayPtr Table of display points
[in] screenPtr Table of adc values reflecting display points
Returns
Returns OK if calibration table is set.
Definition at line 410 of file touch.c.
References calibrationMatrix.
TOUCH_Pos_TypeDef* TOUCH_GetPos (void)
Returns current touch position and state.
Returns
Current touch position and state
Definition at line 372 of file touch.c.
References ADC0, ADC_IF_SINGLE, ADC_IntDisable(), ADC_IntEnable(), TOUCH_Pos_TypeDef::adcx, TOUCH_Pos_TypeDef::adcy, TOUCH_Pos_TypeDef::pen, TOUCH_Pos_TypeDef::x, and TOUCH_Pos_TypeDef::y.
void TOUCH_Init (TOUCH_Config_TypeDef * config)
Initialize touch panel driver.
Parameters
config Driver configuration data.
Definition at line 340 of file touch.c.
References _ADC_IF_MASK, ADC0, ADC0_IRQn, ADC_IF_SINGLE, ADC_Init(), ADC_INIT_DEFAULT, ADC_InitSingle(), ADC_IntClear(), ADC_IntDisable(), ADC_IntEnable(), ADC_PrescaleCalc(), ADC_Start(), ADC_Y, adcRefVDD, adcResOVS, adcStartSingle, BSP_PeripheralAccess(), BSP_TOUCH, CMU_ClockEnable(), cmuClock_ADC0, TOUCH_Config_TypeDef::frequency, TOUCH_Config_TypeDef::ignore, ADC_InitSingle_TypeDef::input, TOUCH_Config_TypeDef::oversampling, ADC_Init_TypeDef::ovsRateSel, ADC_Init_TypeDef::prescale, ADC_InitSingle_TypeDef::reference, and ADC_InitSingle_TypeDef::resolution.
int TOUCH_IsBusy (void)
Check status of the touch panel.
Returns
0 if panel is idle (not touched).
Definition at line 318 of file touch.c.
References GPIO_PinInGet(), TOUCH_X2_PIN, and TOUCH_X2_PORT.
void TOUCH_RegisterUpcall (TOUCH_Upcall_TypeDef * new_upcall)
Register upcall which will be call every position or state change.
Parameters
[in] new_upcall Pointer to upcall function
Definition at line 392 of file touch.c.