EZR32 Leopard Gecko Software Documentation: C:/work/s025_sw/emdrv/tempdrv/src/tempdrv.c File Reference
tempdrv.c File Reference
Detailed Description
TEMPDRV API implementation.
Version
4.3.0
License
(C) Copyright 2014 Silicon Labs, http://www.silabs.com
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
The origin of this software must not be misrepresented; you must not claim that you wrote the original software.
Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
This notice may not be removed or altered from any source distribution.
DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: Silicon Labs has no obligation to support this Software. Silicon Labs is providing the Software "AS IS", with no express or implied warranties of any kind, including, but not limited to, any implied warranties of merchantability or fitness for any particular purpose or warranties against infringement of any proprietary rights of a third party.
Silicon Labs will not be liable for any consequential, incidental, or special damages, or any other relief, or for any claim by any third party, arising from your use of this Software.
Definition in file tempdrv.c.
#include "em_device.h"
#include "em_system.h"
#include "em_emu.h"
#include "string.h"
#include "tempdrv.h"
Data Structures
struct TEMPDRV_CallbackSet_t
Macros
#define errataInit()
#define TEMPDRV_CALLBACK_DEPTH (TEMPDRV_INT_CALLBACK_DEPTH + TEMPDRV_CUSTOM_CALLBACK_DEPTH)
#define TEMPDRV_CUSTOM_CALLBACK_INDEX TEMPDRV_INT_CALLBACK_DEPTH
#define TEMPDRV_INT_CALLBACK_DEPTH 0
Functions
static Ecode_t addCallback (TEMPDRV_CallbackSet_t *set, int8_t temp, TEMPDRV_Callback_t callback)
Attempt to add a callback to the set, error if no space or invalid temp.
static bool checkForDuplicates (TEMPDRV_CallbackSet_t *set, int8_t temp)
Check if another callback has registered the same temperature.
static Ecode_t convertEMUtoTEMP (uint8_t emu, int8_t *temp)
Convert EMU value to degrees Celsius.
static Ecode_t convertTEMPtoEMU (int8_t temp, uint8_t *emu)
Convert degrees Celsius to EMU value.
static void disableInterrupts ()
Turn off interrupts.
void EMU_IRQHandler (void)
EMU Interrupt Handler.
static int8_t findCallbackSpace (TEMPDRV_CallbackSet_t *set)
Find an empty spot for callback in set.
static bool removeCallback (TEMPDRV_CallbackSet_t *set, TEMPDRV_Callback_t callback)
Remove a callback from the set.
Ecode_t TEMPDRV_DeInit ()
De-initialize the TEMP driver.
Ecode_t TEMPDRV_Enable (bool enable)
Enable the TEMP driver.
uint8_t TEMPDRV_GetActiveCallbacks (TEMPDRV_LimitType_t limit)
Get the number of active callbacks for a limit.
int8_t TEMPDRV_GetTemp ()
Get the current temperature.
Ecode_t TEMPDRV_Init ()
Initialize the TEMP driver.
void TEMPDRV_IRQHandler (void)
TEMPDRV Interrupt Handler.
Ecode_t TEMPDRV_RegisterCallback (int8_t temp, TEMPDRV_LimitType_t limit, TEMPDRV_Callback_t callback)
Register a callback in the TEMP driver.
Ecode_t TEMPDRV_UnregisterCallback (TEMPDRV_Callback_t callback)
Unregister a callback in the TEMP driver.
static void updateInterrupts ()
Update interrupts based on active callbacks.
Variables
static int32_t calibrationEMU
static int32_t calibrationTEMP
static uint8_t fallbackEMU = 0x90
static uint8_t fallbackTEMP = 25
static TEMPDRV_CallbackSet_t * highCallback
static TEMPDRV_CallbackSet_t * lowCallback
static TEMPDRV_CallbackSet_t nullCallback = {NULL, 0}
static bool TEMPDRV_EnableState = false
static bool TEMPDRV_InitState = false
static TEMPDRV_CallbackSet_t tempdrvHighCallbacks [TEMPDRV_CALLBACK_DEPTH]
static TEMPDRV_CallbackSet_t tempdrvLowCallbacks [TEMPDRV_CALLBACK_DEPTH]
Function Documentation
static Ecode_t addCallback (TEMPDRV_CallbackSet_t * set, int8_t temp, TEMPDRV_Callback_t callback) static
Attempt to add a callback to the set, error if no space or invalid temp.
Parameters
[in] set Callback set to add callback to
[in] temp Temperature to register callback at
[in] callback Callback function
Returns
ECODE_EMDRV_TEMPDRV_OK on success.
Definition at line 263 of file tempdrv.c.
References TEMPDRV_CallbackSet_t::callback, convertTEMPtoEMU(), ECODE_EMDRV_TEMPDRV_NO_SPACE, ECODE_EMDRV_TEMPDRV_OK, findCallbackSpace(), and updateInterrupts().
Referenced by TEMPDRV_RegisterCallback().
static bool checkForDuplicates (TEMPDRV_CallbackSet_t * set, int8_t temp) static
Check if another callback has registered the same temperature.
Parameters
[in] set Callback set to search
[in] temp Temperature to match
Returns
True if duplicate is found.
Definition at line 320 of file tempdrv.c.
References convertTEMPtoEMU().
Referenced by TEMPDRV_RegisterCallback().
static Ecode_t convertEMUtoTEMP (uint8_t emu, int8_t * temp) static
Convert EMU value to degrees Celsius.
Parameters
[in] emu EMU value to convert
[in] temp Pointer to store temperature
Returns
ECODE_EMDRV_TEMPDRV_OK on success.
Definition at line 351 of file tempdrv.c.
References ECODE_EMDRV_TEMPDRV_OK, ECODE_EMDRV_TEMPDRV_TEMP_OVER, and ECODE_EMDRV_TEMPDRV_TEMP_UNDER.
Referenced by TEMPDRV_GetTemp().
static Ecode_t convertTEMPtoEMU (int8_t temp, uint8_t * emu) static
Convert degrees Celsius to EMU value.
Parameters
[in] temp Temperature to convert
[in] emu Pointer to store EMU value
Returns
ECODE_EMDRV_TEMPDRV_OK on success.
Definition at line 379 of file tempdrv.c.
References ECODE_EMDRV_TEMPDRV_OK, ECODE_EMDRV_TEMPDRV_TEMP_OVER, and ECODE_EMDRV_TEMPDRV_TEMP_UNDER.
Referenced by addCallback(), and checkForDuplicates().
static int8_t findCallbackSpace (TEMPDRV_CallbackSet_t * set) static
Find an empty spot for callback in set.
Parameters
[in] set Callback set to search
Returns
EZR32 Leopard Gecko Software Documentation of empty space if found, -1 if none
Definition at line 237 of file tempdrv.c.
Referenced by addCallback().
static bool removeCallback (TEMPDRV_CallbackSet_t * set, TEMPDRV_Callback_t callback) static
Remove a callback from the set.
Parameters
[in] set Callback set to remove callback from
[in] callback Callback function
Returns
True on success.
Definition at line 292 of file tempdrv.c.
References TEMPDRV_CallbackSet_t::callback, TEMPDRV_CallbackSet_t::temp, and updateInterrupts().
Referenced by TEMPDRV_UnregisterCallback().