EFM32 Pearl Gecko 12 Software Documentation: D:/jenkins-slave/workspaces/Executor-0/super/hardware/kit/common/drivers/si114x_uv_index.h File Reference
si114x_uv_index.h File Reference
Detailed Description
Si114x UV Index measurement.
Version
5.1.1
License
Copyright 2015 Silicon Labs, Inc. http://www.silabs.com
This file is licensed under the Silabs License Agreement. See the file "Silabs_License_Agreement.txt" for details. Before using this software for any purpose, you must agree to the terms of that agreement.
Definition in file si114x_uv_index.h.
Functions
int Si114x_ConfigureUV (int fullInit, HANDLE *handle)
Initializes and configures the Si1146 sensor for UV index measurements.
int Si114x_EnableVisRange (int vis_range_bit)
Set the VIS_RANGE bit of the optical sensor Si114x.
int Si114x_MeasureUVIndex (u16 *uvIndex)
Reads the UV index measurement data from the Si114x.
Function Documentation
int Si114x_ConfigureUV (int fullInit, HANDLE * handle)
Initializes and configures the Si1146 sensor for UV index measurements.
Parameters
[in] fullInit The I2C peripheral to use (not used).
[in] handle The si114x handle for programmer's toolkit
Returns
Returns 0 on success.
Definition at line 110 of file si114x_uv_index.c.
References si114x_get_calibration(), si114x_handle, si114x_set_ucoef(), Si114xParamSet(), Si114xReset(), Si114xWriteToRegister(), and UV_TASKLIST.
int Si114x_EnableVisRange (int vis_range_bit)
Set the VIS_RANGE bit of the optical sensor Si114x.
Parameters
[in] vis_range_bit the boolean value to set the bit to
Returns
Returns 0.
Definition at line 88 of file si114x_uv_index.c.
References si114x_handle, and Si114xParamSet().
int Si114x_MeasureUVIndex (u16 * uvIndex)
Reads the UV index measurement data from the Si114x.
Parameters
[out] uvIndex The UV index read from the sensor
Returns
Returns 0.
Definition at line 40 of file si114x_uv_index.c.
References si114x_handle, Si114xPsAlsForce(), Si114xReadFromRegister(), and Si114xWriteToRegister().