EZR32 Happy Gecko Software Documentation: PN9_Plugin
PN9_Plugin
EMDRV » EZRADIODRV » Plugin_System
Detailed Description
Pseudo random transmit plugin, see Plugin System Layer for detailed documentation.
.
Data Structures
struct EZRADIODRV_Pn9Handle
EzRadio PN9 plug-in instance initialization and handler structure.
Macros
#define EZRADIODRV_PN9_PLUGIN_INIT_DEFAULT
Configuration data for EzRadio PN9 plug-in.
Typedefs
typedef struct EZRADIODRV_Pn9Handle EZRADIODRV_Pn9Handle_t
EzRadio PN9 plug-in instance initialization and handler structure.
Functions
Ecode_t ezradioStartPn9 (EZRADIODRV_Handle_t radioHandle)
Starts PN9 transmission with the radio configurations from the radioHandle parameter.
Ecode_t ezradioStopPn9 (void)
Stops PN9 carrier transmission.
Macro Definition Documentation
#define EZRADIODRV_PN9_PLUGIN_INIT_DEFAULT
Value:
{                               /* PN9                              */  \
  0,                            /* Channel                          */  \
},
Configuration data for EzRadio PN9 plug-in.
Definition at line 75 of file ezradio_pn9_plugin.h.
Function Documentation
Ecode_t ezradioStartPn9 (EZRADIODRV_Handle_t radioHandle)
Starts PN9 transmission with the radio configurations from the radioHandle parameter.
Parameters
radioHandle Handler of the EzRadio driver instance where channel configuration is set.
Returns
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 56 of file ezradio_pn9_plugin.c.
References EZRADIODRV_Pn9Handle::channel, ECODE_EMDRV_EZRADIODRV_ILLEGAL_HANDLE, ECODE_EMDRV_EZRADIODRV_OK, ECODE_EMDRV_EZRADIODRV_TRANSMIT_FAILED, ezradio_get_int_status(), ezradio_request_device_state(), ezradio_start_tx(), and EZRADIODRV_HandleData::pn9.
Ecode_t ezradioStopPn9 (void)
Stops PN9 carrier transmission.
Returns
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 88 of file ezradio_pn9_plugin.c.
References ECODE_EMDRV_EZRADIODRV_OK, and ezradio_change_state().